FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /workspace
COPY . .
RUN mvn -pl api -am package -DskipTests

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /workspace/api/target/balancerx-api-*.jar app.jar
ENTRYPOINT ["java","-jar","/app/app.jar"]
