spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/balancerx
    username: balancerx
    password: balancerx
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
management:
  endpoints:
    web:
      exposure:
        include: health,info
balancerx:
  storage:
    root: storage
