name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Temurin 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
      - name: Build & Test
        run: mvn -B verify
      - name: JaCoCo Report
        if: always()
        run: |
          echo "JaCoCo report generado en target/site/jacoco"
      - name: Package API Docker image
        run: docker build -f Dockerfile.api -t balancerx/api:ci .
